
'use client';

import jsPDF from 'jspdf';
import { SongStructure, ChordVoicing } from './music-theory';

export interface LeadSheetData {
  title: string;
  mood: string;
  skillLevel: string;
  structure: SongStructure;
  chordVoicings: Record<string, ChordVoicing>;
}

export function generateLeadSheetPDF(data: LeadSheetData): void {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  let yPosition = 20;

  // Title
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Jazz Funk Lead Sheet', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Song Info
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Mood: ${data.mood}`, 20, yPosition);
  pdf.text(`Skill Level: ${data.skillLevel}`, pageWidth - 80, yPosition);
  yPosition += 10;
  pdf.text(`Tempo: ${data.structure.tempo}`, 20, yPosition);
  yPosition += 20;

  // Song Structure
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Song Structure', 20, yPosition);
  yPosition += 10;

  data.structure.sections.forEach(section => {
    // Section header
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`${section.name} (${section.measures} measures)`, 20, yPosition);
    yPosition += 8;

    section.progressions.forEach(progression => {
      // Chord progression
      pdf.setFont('helvetica', 'normal');
      pdf.text(`${progression.chords.join(' - ')}`, 30, yPosition);
      yPosition += 6;
      pdf.setFontSize(10);
      pdf.text(`Rhythm: ${progression.rhythm}`, 30, yPosition);
      yPosition += 10;
      pdf.setFontSize(12);
    });

    yPosition += 5;
    
    // Check if we need a new page
    if (yPosition > pageHeight - 50) {
      pdf.addPage();
      yPosition = 20;
    }
  });

  yPosition += 10;

  // Chord Voicings
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Chord Voicings & Fingerings', 20, yPosition);
  yPosition += 15;

  Object.entries(data.chordVoicings).forEach(([chordName, voicing]) => {
    if (!voicing) return;
    
    // Check if we need a new page
    if (yPosition > pageHeight - 60) {
      pdf.addPage();
      yPosition = 20;
    }

    // Chord name
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text(voicing.name, 20, yPosition);
    yPosition += 8;

    // Notes
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Notes: ${voicing.notes.join(', ')}`, 30, yPosition);
    yPosition += 6;

    // Keyboard fingering
    pdf.text('Keyboard:', 30, yPosition);
    yPosition += 4;
    voicing.keyboardFingering.forEach(fingering => {
      pdf.text(`  ${fingering}`, 40, yPosition);
      yPosition += 4;
    });

    // Guitar fingering
    pdf.text('Guitar:', 30, yPosition);
    yPosition += 4;
    pdf.text(`  Frets: ${voicing.guitarFingering.frets.join('-')}`, 40, yPosition);
    yPosition += 4;
    pdf.text(`  Strings: ${voicing.guitarFingering.strings.join(', ')}`, 40, yPosition);
    yPosition += 4;

    if (voicing.guitarFingering.barres && voicing.guitarFingering.barres.length > 0) {
      voicing.guitarFingering.barres.forEach(barre => {
        pdf.text(`  Barre: Fret ${barre.fret}, Strings ${barre.strings.join(', ')}`, 40, yPosition);
        yPosition += 4;
      });
    }

    yPosition += 8;
  });

  // Footer
  const footerY = pageHeight - 15;
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'italic');
  pdf.text('Generated by Jazz Funk Song Chord Progression Creator', pageWidth / 2, footerY, { align: 'center' });

  // Download the PDF
  const timestamp = new Date().toISOString().slice(0, 19).replace(/:/g, '-');
  pdf.save(`jazz-funk-leadsheet-${data.mood.toLowerCase()}-${timestamp}.pdf`);
}

export function generateSimplifiedLeadSheet(data: LeadSheetData): string {
  let leadSheet = `JAZZ FUNK LEAD SHEET\n`;
  leadSheet += `========================\n\n`;
  leadSheet += `Mood: ${data.mood}\n`;
  leadSheet += `Skill Level: ${data.skillLevel}\n`;
  leadSheet += `Tempo: ${data.structure.tempo}\n\n`;

  leadSheet += `SONG STRUCTURE:\n`;
  leadSheet += `---------------\n`;

  data.structure.sections.forEach(section => {
    leadSheet += `\n${section.name.toUpperCase()} (${section.measures} measures)\n`;
    section.progressions.forEach(progression => {
      leadSheet += `${progression.chords.join(' | ')}\n`;
      leadSheet += `Rhythm: ${progression.rhythm}\n`;
    });
  });

  leadSheet += `\n\nCHORD VOICINGS:\n`;
  leadSheet += `===============\n`;

  Object.entries(data.chordVoicings).forEach(([chordName, voicing]) => {
    if (!voicing) return;
    
    leadSheet += `\n${voicing.name}\n`;
    leadSheet += `Notes: ${voicing.notes.join(', ')}\n`;
    leadSheet += `Keyboard: ${voicing.keyboardFingering.join(' | ')}\n`;
    leadSheet += `Guitar: Frets ${voicing.guitarFingering.frets.join('-')}\n`;
  });

  return leadSheet;
}
